baseURL : 'https://ci-yu.top'
languageCode : 'en-us'
title : 'CI-YU Blog'
paginate : 10
theme : "PaperMod"
buildDrafts: false
UseHugoToc: true
googleAnalytics: G-S4X5YV8EB6
languages:
    en:
        languageName: "English"
        weight: 1
        # taxonomies:
        #   category: categories
        #   tag: tags
        #   series: series
        menu:
          main:
          - identifier: Dotnet
          name: Dotnet
          url: /dotnet/
          weight: 10  
        - identifier: Flutter
          name: Flutter
          url: /flutter/
         weight: 15
        - identifier: 軟實力
          name: SoftSkills
          url: /softskills/
          weight: 30
        - identifier: Search
          name: Search
          url: /search/
          weight: 40
        - identifier: Tags
          name: Tags
          url: /tags/
          weight: 50
        - identifier: Archives
          name: Archives
          url: /archives/
          weight: 60


outputs:
    home:
        - HTML
        - RSS
        - JSON
params:
  env: production
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: 分享技術與有趣的事物
  socialIcons:
    - name: github
      url: "https://github.com/CI-YU"
    - name: linkedin
      url: "https://www.linkedin.com/in/ci-yu-huang-8a75a21b0/"
  ShowBreadCrumbs: true
  # 顯示文章大綱
  # showtoc: true
  hidefooter: true
  ShowCodeCopyButtons: true
  mainSections:
    - flutter
    - drafts
    - softpower
    - dotnet
    - posts
  assets: 
    disableHLJS: true 
    favicon: "/assets/favicon.png"
    favicon16x16: "/assets/favicon.png"
    favicon32x32: "/assets/favicon.png"
    apple_touch_icon: "/assets/favicon.png" 
    safari_pinned_tab: "/assets/favicon.png"